// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Product struct {
	ID          int32           `json:"id"`
	Name        string          `json:"name"`
	Duration    sql.NullInt32   `json:"duration"`
	Price       sql.NullFloat64 `json:"price"`
	Description sql.NullString  `json:"description"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
	DeletedAt   sql.NullTime    `json:"deleted_at"`
}

type User struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Active    sql.NullBool `json:"active"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type UserSubscription struct {
	ID         uuid.UUID       `json:"id"`
	UserID     uuid.UUID       `json:"user_id"`
	ProductID  sql.NullInt32   `json:"product_id"`
	TrialStart sql.NullTime    `json:"trial_start"`
	TrialEnd   sql.NullTime    `json:"trial_end"`
	StartDate  sql.NullTime    `json:"start_date"`
	EndDate    sql.NullTime    `json:"end_date"`
	Discount   sql.NullFloat64 `json:"discount"`
	Tax        sql.NullFloat64 `json:"tax"`
	Active     sql.NullBool    `json:"active"`
	CreatedAt  sql.NullTime    `json:"created_at"`
	PausedAt   sql.NullTime    `json:"paused_at"`
	UpdatedAt  sql.NullTime    `json:"updated_at"`
	DeletedAt  sql.NullTime    `json:"deleted_at"`
}
