// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CancelSubscription(ctx context.Context, id uuid.UUID) (UserSubscription, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (UserSubscription, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetProducts(ctx context.Context) ([]Product, error)
	GetSubscriptionByID(ctx context.Context, id uuid.UUID) (UserSubscription, error)
	PauseSubscription(ctx context.Context, id uuid.UUID) (UserSubscription, error)
}

var _ Querier = (*Queries)(nil)
