// Code generated by sqlc. DO NOT EDIT.
// source: user_subscription.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, product_id, trial_start, trial_end, start_date, end_date, discount, tax, active, created_at, paused_at, updated_at, deleted_at FROM user_subscriptions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (UserSubscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByID, id)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.TrialStart,
		&i.TrialEnd,
		&i.StartDate,
		&i.EndDate,
		&i.Discount,
		&i.Tax,
		&i.Active,
		&i.CreatedAt,
		&i.PausedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
